# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vin', models.CharField(max_length=255)),
                ('license_plate', models.CharField(max_length=20)),
                ('purchase_date', models.DateField()),
                ('sell_date', models.DateField()),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('tire_size', models.IntegerField()),
                ('tire_pressure', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
