# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='purchase_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='sell_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='tire_pressure',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='tire_size',
            field=models.IntegerField(null=True),
        ),
    ]
