# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='favourite_snack',
        ),
    ]
