# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FillUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odometer', models.IntegerField(blank=True, null=True)),
                ('unit_cost_per', models.FloatField(blank=True, null=True)),
                ('unit_quantity', models.FloatField(blank=True, null=True)),
                ('total_cost', models.FloatField(blank=True, null=True)),
                ('fuel_economy', models.FloatField(blank=True, null=True)),
                ('filled_up', models.CharField(choices=[(1, 'Partial'), (2, 'Full')], max_length=10)),
                ('octane', models.IntegerField(choices=[(86, 86), (87, 87), (89, 89), (92, 92), ('diesel', 'Diesel')])),
                ('fuel_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fuel.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
