# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_fillup_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillup',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fillup',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fillup',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
