# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-07 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0003_auto_20160903_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillup',
            name='filled_up',
            field=models.IntegerField(choices=[(1, 'Partial'), (2, 'Full')]),
        ),
    ]
