# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_auto_20160903_0108'),
        ('fuel', '0004_auto_20160907_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillup',
            name='car_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car.Car'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fillup',
            name='filled_up',
            field=models.IntegerField(choices=[(1, 'Partial'), (2, 'Full')], default=1),
        ),
        migrations.AlterField(
            model_name='fillup',
            name='octane',
            field=models.IntegerField(choices=[(87, 87), (89, 89), (92, 92), ('diesel', 'Diesel')], default=87),
        ),
    ]
