# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('fuel', '0006_auto_20160908_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillup',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.MyProfile'),
            preserve_default=False,
        ),
    ]
