# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0007_fillup_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.MyProfile', to_field='user_id'),
        ),
    ]
