# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0008_auto_20160913_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillup',
            name='octane',
            field=models.IntegerField(blank=True, choices=[(87, 87), (89, 89), (92, 92), ('diesel', 'Diesel')], default=87),
        ),
    ]
