# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0011_auto_20160914_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='fillup',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fillup',
            name='services',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fillup',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
