# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0012_auto_20160914_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillup',
            name='octane',
            field=models.IntegerField(blank=True, choices=[(87, 87), (89, 89), (92, 92), ('diesel', 'Diesel')], default=87, null=True),
        ),
    ]
