# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0014_auto_20160914_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillup',
            name='octane',
            field=models.CharField(blank=True, choices=[('', ''), (87, 87), (89, 89), (92, 92), ('diesel', 'Diesel')], default=87, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fillup',
            name='odometer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
